# CircleCI Config Policy Configuration
# Defines how and when security policies are enforced

version: 1

policies:
  security-policy:
    # Path to the Rego policy file
    source: ./security-policy.rego

    # Enforcement level
    # - "hard_fail": Block workflow execution completely
    # - "soft_fail": Allow execution but show warnings
    enforcement_level: hard_fail

    # When to apply this policy
    enabled_for:
      - pull_requests
      - scheduled_pipelines
      - manual_triggers

    # Exclude these scenarios (trusted paths)
    excluded_for:
      - main_branch_pushes_from_collaborators

    # Additional metadata
    metadata:
      description: "Security policy for open source contributions"
      owner: "platform-team"
      version: "1.0.0"
# Optional: Additional policies can be defined here
#policies:
#  dependency-policy:
#    source: ./dependency-policy.rego
#    enforcement_level: soft_fail
